### ISSUE TITLE
Error from Augury

### ISSUE THREAD

**Issue by jcubic** [ng-select/ng-select#1080]
**Describe the bug**
If you open demo in Augury (Angular 2+ debugger/inpsector) it show error

```
zone.js:665 Unhandled Promise rejection: Cannot read property 'ngInjectableDef' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'ngInjectableDef' of null
    at zi (core.js:8360)
    at t.get (core.js:9064)
    at Object.Ms [as resolveDep] (core.js:9429)
    at t.get (core.js:8923)
    at Function.t.getComponentDescription (backend.js:31)
    at Object.e.transform (backend.js:31)
    at backend.js:31
    at Array.forEach (<anonymous>)
    at O (backend.js:31)
    at Object.e.transform (backend.js:31)
    at Object.e.transformToTree (backend.js:31)
    at backend.js:31
    at Array.map (<anonymous>)
    at Object.e.createTreeFromElements (backend.js:31)
    at Object.<anonymous> (backend.js:31)
    at backend.js:31
    at Object.next (backend.js:31)
    at backend.js:31
    at new t (zone.js:891)
    at n (backend.js:31)
    at D (backend.js:31)
    at e._next (backend.js:31)
    at e.__tryOrUnsub (Subscriber.js:195)
    at e.next (Subscriber.js:133)
    at e._next (Subscriber.js:77)
    at e.next (Subscriber.js:54)
    at e.notifyNext (mergeMap.js:79)
    at e._next (InnerSubscriber.js:15)
    at e.next (Subscriber.js:54)
    at core.js:4478
    at t.invoke (zone.js:388)
    at n.run (zone.js:138)
    at t.runOutsideAngular (core.js:3783)
    at t._subscribe (core.js:4477)
    at t._trySubscribe (Observable.js:42)
    at t.subscribe (Observable.js:28)
    at subscribeTo.js:21
    at s (subscribeToResult.js:6)
    at e._innerSub (mergeMap.js:70)
    at e._tryNext (mergeMap.js:67)
    at e._next (mergeMap.js:50)
    at e.next (Subscriber.js:54)
    at t._subscribe (subscribeToArray.js:5)
    at t._trySubscribe (Observable.js:42)
    at t.subscribe (Observable.js:28)
    at t.call (mergeMap.js:28)
    at t.subscribe (Observable.js:23)
    at backend.js:31
    at M (backend.js:31)
    at backend.js:31
    at t.invoke (zone.js:388)
    at n.run (zone.js:138)
    at zone.js:872
    at t.invokeTask (zone.js:421)
    at n.runTask (zone.js:188)
    at y (zone.js:595)
    at n.invokeTask (zone.js:500)
    at i.useG.invoke (zone.js:485)
    at e.args.(/anonymous function) (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:62:141) TypeError: Cannot read property 'ngInjectableDef' of null
    at zi (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:394:812)
    at t.get (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:409:9171)
    at Object.Ms [as resolveDep] (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:416:3143)
    at t.get (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:409:6240)
    at Function.t.getComponentDescription (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:54003)
    at Object.e.transform (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:170229)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:170546
    at Array.forEach (<anonymous>)
    at O (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:170501)
    at Object.e.transform (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:170764)
    at Object.e.transformToTree (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:172295)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:172518
    at Array.map (<anonymous>)
    at Object.e.createTreeFromElements (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:172491)
    at Object.<anonymous> (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260587)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:259303
    at Object.next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:259408)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:258352
    at new t (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:13685)
    at n (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:258129)
    at D (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260513)
    at e._next (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261910)
    at e.__tryOrUnsub (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:3975)
    at e.next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:3120)
    at e._next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:2172)
    at e.next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:1843)
    at e.notifyNext (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:901:8791)
    at e._next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:6458)
    at e.next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:1843)
    at https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:214:4076
    at t.invoke (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:7001)
    at n.run (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:2171)
    at t.runOutsideAngular (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:200:3086)
    at t._subscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:214:4045)
    at t._trySubscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:5391)
    at t.subscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:5177)
    at https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:1082:27031
    at s (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:6771)
    at e._innerSub (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:901:8592)
    at e._tryNext (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:901:8516)
    at e._next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:901:8339)
    at e.next (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:1843)
    at t._subscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:1082:27964)
    at t._trySubscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:5391)
    at t.subscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:5177)
    at t.call (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:901:8018)
    at t.subscribe (https://ng-select.github.io/ng-select/js/app.35e5bcb46d34949f02d4.js:745:5049)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261888
    at M (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:260086)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:261776
    at t.invoke (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:7001)
    at n.run (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:2171)
    at https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:13481
    at t.invokeTask (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:7685)
    at n.runTask (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:2865)
    at y (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:9934)
    at n.invokeTask (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:8828)
    at i.useG.invoke (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:31:8690)
    at e.args.(anonymous function) (https://ng-select.github.io/ng-select/js/polyfills.35e5bcb46d34949f02d4.js:62:141)
```
**Reproducbile example**

[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
* Install Augury
* Open https://ng-select.github.io/ng-select
* Open Dev tools
* switch to Agury

**Expected behavior**
Augury works and you can debug/introspect Angular app

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 72

Not sure if this is Augury or ng-select bug.

**Comment by varnastadeus** [comment]
this issue should be probably created in augury repo, not this one
