### ISSUE TITLE
When lazy-loading (with 'IVY') a module and component that uses ng-select, I get the error: "No provider for InjectionToken ng-select-selection-model"

### ISSUE THREAD

**Issue by boltex** [ng-select/ng-select#1464]
**Describe the bug**
I'm using angular's new IVY compiler, along with the new lazy-loading functionality (Description and example here: https://www.debugbear.com/blog/lazy-loading-angular-components-without-a-router)
When lazy-loading a module and adding an instance of a component to my app, the ng-select does not appear in the component and I get this error in the console: 
`core.js:6354 ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionToken ng-select-selection-model -> InjectionToken ng-select-selection-model -> InjectionToken ng-select-selection-model]: 
  NullInjectorError: No provider for InjectionToken ng-select-selection-model!
    at NullInjector.get (http://localhost:4200/vendor.js:8736:27)
    at R3Injector.get (http://localhost:4200/vendor.js:24378:33)
    at R3Injector.get (http://localhost:4200/vendor.js:24378:33)
    at R3Injector.get (http://localhost:4200/vendor.js:24378:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:40184:33)
    at Object.get (http://localhost:4200/vendor.js:38095:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:12876:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:28245:12)
    at NodeInjectorFactory.NgSelectComponent_Factory [as factory] (http://localhost:4200/lazy-lazy-module.js:4143:398)
    at getNodeInjectable (http://localhost:4200/vendor.js:13021:44)`

**Reproducible example**
see https://github.com/boltex/ivy-lazyload-test for a minimal repo exposing this bug.

**To Reproduce** 
1. clone the example repo `git clone https://github.com/boltex/ivy-lazyload-test`
2. run `npm install` to get all dependencies
3. run `ng serve`

**Expected behavior**
When trying this locally with ng serve, when the program loads in your browser, press the "Lazy load module & add instance of component below" button. (This will add some components instance into the app) The component should have an ng-select in it. It doesn't and forementionned error appears in the console.

**Note**
Ignore the first error in the console: **Uncaught TypeError: ng.probe is not a function**
It is a normal error to get when using angular 9 because augury assumes angular dev mode is active if window.ng exists, but ivy doesn't export probe right now.

**Screenshots**
![image](https://user-images.githubusercontent.com/847716/70572586-115ecf00-1b6e-11ea-80b0-351f7a1d68ae.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [78.0.3904.108 (Official Build) (64-bit)]

Thanks for your time and attention to this issue !

**Comment by boltex** [comment]
I've found a solution with @herodev's 'hero-loader' component. 
(See their relatively short source code for the additional techniques it uses: https://github.com/herodevs/herodevs-packages/tree/master/projects)

The method I was using was not fully compatible with all methods of integrating componnent, 3rd party or otherwise, into an existing application by lazy-loading.  (Not using routing)

I've updated my repository https://github.com/boltex/ivy-lazyload-test with a working example where you can add, and remove, arbitrary number of different modules and components into an opened application without changing routes.

**Comment by helderabreu** [comment]
Hi @boltex. 
Did you find a way to solve this issue?
I'm facing the same problem right now.

**Comment by mirackle-spb** [comment]
The problem is still there. I am using 4.0.4 and do not have possibility to upgrade to angular 10.
Any fix in ng-select?

**Comment by tayambamwanza** [comment]
@boltex Would you consider re-opening this issue? the problem still exists for me and I'm using angular 11.
While I was in the lazy loaded route it works, but I had the select as part of a form within a model, it seems that it might be because of how ivy doesn't have the whole entryComponent system anymore?

**Comment by Maksiemens** [comment]
I have same issue

**Comment by Xstream007** [comment]
I had the same issue. I figured out that the issue was due to my parent-child relationship between components. I was opening an another component within a component. When I imported NgSelectModule within my parent component module, also that I added NgSelectModule, NgOption imports in the component.ts of the parent component, my issue was fixed.

Not in all parent-child relationship this issue occurred. It occurred when I was displaying some contents in the parent component as well as the child component. I guess the issue was due to parent component being live.

In parent component module - 

    import { NgSelectModule } from '@ng-select/ng-select';
    ....
    @NgModule( {
        imports: [
        ....
        NgSelectModule
    ],

In parent component component.ts - 

    import { NgSelectModule, NgOption } from '@ng-select/ng-select';

**Comment by Jelledb** [comment]
I have the same issue. Even though the above solution fixed the issue for me it is extremely strange to declare a module import in a component file, this also requires linting hacks etc.

**Comment by adam-marshall** [comment]
same issue here too - I agree this should be reopened

**Comment by Celtian** [comment]
I agree with @adam-marshall. This is serious critical bug and should be reopened.

**Comment by Celtian** [comment]
I have already found dirty solution.

1) Copy https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/selection-model.ts into your Angular app. **It is not exposed as public**, that's the reason why you can't use it. `DefaultSelectionModelFactory` that's the function you need.

2) Use it as a provider in your lazy loaded component.

```
@Component({
  selector: 'app-lazy-loaded-modal',
  templateUrl: './lazy-loade-modal.component.html',
  styleUrls: ['./lazy-loaded-modal.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    FormBuilder,
    { provide: SELECTION_MODEL_FACTORY, useValue: DefaultSelectionModelFactory }
  ],
})
```

In my opinion, possible convenient solution can be to expose `DefaultSelectionModelFactory` and let mention on lazy loaded components and modules in official documentation.

**Comment by Jelledb** [comment]
@github-actions that is fake news. It's still an issue

**Comment by bjornharvold** [comment]
Yes, just experienced exactly the same error as described here.

**Comment by julian-forster** [comment]
same

**Comment by Sarathcani999** [comment]
Any updates on this?

**Comment by hpardess** [comment]
Facing same error 

```
list-user.component.html:68 ERROR NullInjectorError: R3InjectorError(Environment Injector)[InjectionToken ng-select-selection-model -> InjectionToken ng-select-selection-model]: 
  NullInjectorError: No provider for InjectionToken ng-select-selection-model!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at ChainedInjector.get (core.mjs:15723:36)
    at lookupTokenUsingModuleInjector (core.mjs:5730:39)
    at getOrCreateInjectable (core.mjs:5778:12)
    at ɵɵdirectiveInject (core.mjs:11050:19)
    at NodeInjectorFactory.NgSelectComponent_Factory [as factory] (ng-select-ng-select.mjs:3381:150)
    at getNodeInjectable (core.mjs:5984:44)
    at instantiateAllDirectives (core.mjs:11907:27)
```
Angular v17.3.0

**Comment by hpardess** [comment]
> I had the same issue. I figured out that the issue was due to my parent-child relationship between components. I was opening an another component within a component. When I imported NgSelectModule within my parent component module, also that I added NgSelectModule, NgOption imports in the component.ts of the parent component, my issue was fixed.
> 
> Not in all parent-child relationship this issue occurred. It occurred when I was displaying some contents in the parent component as well as the child component. I guess the issue was due to parent component being live.
> 
> In parent component module -
> 
> ```
> import { NgSelectModule } from '@ng-select/ng-select';
> ....
> @NgModule( {
>     imports: [
>     ....
>     NgSelectModule
> ],
> ```
> 
> In parent component component.ts -
> 
> ```
> import { NgSelectModule, NgOption } from '@ng-select/ng-select';
> ```

It helped me... I import the package in app.config.ts of Angular 17  and now it works without any error.

```
import { importProvidersFrom } from '@angular/core';
import { NgSelectModule } from '@ng-select/ng-select';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    importProvidersFrom(NgSelectModule),
  ],
};
```
