### ISSUE TITLE
BREAKS TYPESCRIPT 3.7.4

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1483]
TS version 3.7.4

Problem file was ```@ng-select/ng-select/fesm5/ng-select-ng-select.js```

```
Node Identifier was unexpected.
    at getDeclarationSpaces (/Users/joshua/Projects/aquipa/node_modules/typescript/lib/typescript.js:59394:41)
    at checkExportsOnMergedDeclarations (/Users/joshua/Projects/aquipa/node_modules/typescript/lib/typescript.js:59320:41)
```

offending code appears to be around here:
```
/** @enum {number} */
var KeyCode = {
    Tab: 9,
    Enter: 13,
    Esc: 27,
    Space: 32,
    ArrowUp: 38,
    ArrowDown: 40,
    Backspace: 8,
};
KeyCode[KeyCode.Tab] = 'Tab';
KeyCode[KeyCode.Enter] = 'Enter';
KeyCode[KeyCode.Esc] = 'Esc';
KeyCode[KeyCode.Space] = 'Space';
KeyCode[KeyCode.ArrowUp] = 'ArrowUp';
KeyCode[KeyCode.ArrowDown] = 'ArrowDown';
KeyCode[KeyCode.Backspace] = 'Backspace';
```

**Comment by varnastadeus** [comment]
I don't think angular 8 even supports ts 3.7.4 https://github.com/angular/angular-cli/issues/16071 and since we are depending on angular 8 we won't update it until appropriate angular version supports it.
