### ISSUE TITLE
Closing dropdown error on IE.

### ISSUE THREAD

**Issue by ksamborn** [ng-select/ng-select#303]
Please fill below information if issuing a bug report. 

### Expected behaviour
The dropdown should close without error.

### Actual behaviour
The dropdown does not close and has a console error

Can be seen in the demos and here:

https://plnkr.co/edit/4vVcBF?p=preview
 
```
TypeError: Object doesn't support property or method 'remove'
   at NgDropdownPanelComponent.prototype.ngOnDestroy (http://localhost:8080/vendor.bundle.js:390760:9)
   at callProviderLifecycles (http://localhost:8080/vendor.bundle.js:11390:9)
   at callElementProvidersLifecycles (http://localhost:8080/vendor.bundle.js:11355:13)
   at callLifecycleHooksChildrenFirst (http://localhost:8080/vendor.bundle.js:11339:17)
   at destroyView (http://localhost:8080/vendor.bundle.js:12678:5)
   at ViewContainerRef_.prototype.clear (http://localhost:8080/vendor.bundle.js:10217:13)
   at NgIf.prototype._updateView (http://localhost:8080/vendor.bundle.js:26667:17)
   at ngIf.set (http://localhost:8080/vendor.bundle.js:26620:13)
   at updateProp (http://localhost:8080/vendor.bundle.js:11300:5)
   at checkAndUpdateDirectiveInline (http://localhost:8080/vendor.bundle.js:11009:9)

```

In our application we are a hybrid NG1 app and the ng-select is a downgraded component.  The error causes the entire page to crash.   Only happens on IE

### More Info
ng-select version: 0.23.1

browser: IE

Version: IE 11.248.16299.0
Update Versions: 111.0.51 (KB4074736)

reproducible in demo page: YES, and Plunker

**Comment by anjmao** [comment]
@ksamborn This happens because of this line https://github.com/ng-select/ng-select/blob/14e1da5d7fa9978d0c3d486402da8b25388cfef3/src/ng-select/ng-dropdown-panel.component.ts#L116

IE 11 does not support .remove method, instead it should be `node.parentNode.removeChild(node)`

**Comment by varnastadeus** [comment]
@anjmao I suggest using `Renderer2` in this case
